"""add student checkin access and sessions

Revision ID: 2e552fb58f43
Revises: 34098174559f
Create Date: 2026-04-15 17:11:00.224044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e552fb58f43'
down_revision: Union[str, Sequence[str], None] = '34098174559f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_access_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('access_token_hash', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_access_links_access_token_hash'), 'student_access_links', ['access_token_hash'], unique=True)
    op.create_index(op.f('ix_student_access_links_student_id'), 'student_access_links', ['student_id'], unique=False)
    op.create_table('student_checkin_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=128), nullable=False),
    sa.Column('device_label', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_checkin_sessions_session_token_hash'), 'student_checkin_sessions', ['session_token_hash'], unique=True)
    op.create_index(op.f('ix_student_checkin_sessions_student_id'), 'student_checkin_sessions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_checkin_sessions_student_id'), table_name='student_checkin_sessions')
    op.drop_index(op.f('ix_student_checkin_sessions_session_token_hash'), table_name='student_checkin_sessions')
    op.drop_table('student_checkin_sessions')
    op.drop_index(op.f('ix_student_access_links_student_id'), table_name='student_access_links')
    op.drop_index(op.f('ix_student_access_links_access_token_hash'), table_name='student_access_links')
    op.drop_table('student_access_links')
    # ### end Alembic commands ###
