"""add student daily statuses

Revision ID: 370519233ea3
Revises: 93dcc43eb06b
Create Date: 2026-04-10 11:31:26.369155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370519233ea3'
down_revision: Union[str, Sequence[str], None] = '93dcc43eb06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_daily_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('status_date', sa.Date(), nullable=False),
    sa.Column('status_color', sa.String(length=20), nullable=False),
    sa.Column('last_geolocation_log_id', sa.Integer(), nullable=True),
    sa.Column('last_check_id', sa.Integer(), nullable=True),
    sa.Column('checkins_count', sa.Integer(), nullable=False),
    sa.Column('required_checkins_count', sa.Integer(), nullable=False),
    sa.Column('is_on_place', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['practice_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_check_id'], ['geolocation_checks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_geolocation_log_id'], ['geolocation_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'status_date', name='uq_student_daily_status_student_date')
    )
    op.create_index(op.f('ix_student_daily_statuses_assignment_id'), 'student_daily_statuses', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_student_daily_statuses_status_color'), 'student_daily_statuses', ['status_color'], unique=False)
    op.create_index(op.f('ix_student_daily_statuses_status_date'), 'student_daily_statuses', ['status_date'], unique=False)
    op.create_index(op.f('ix_student_daily_statuses_student_id'), 'student_daily_statuses', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_daily_statuses_student_id'), table_name='student_daily_statuses')
    op.drop_index(op.f('ix_student_daily_statuses_status_date'), table_name='student_daily_statuses')
    op.drop_index(op.f('ix_student_daily_statuses_status_color'), table_name='student_daily_statuses')
    op.drop_index(op.f('ix_student_daily_statuses_assignment_id'), table_name='student_daily_statuses')
    op.drop_table('student_daily_statuses')
    # ### end Alembic commands ###
