"""extend student access links

Revision ID: 38d7a88bda3d
Revises: 2e552fb58f43
Create Date: 2026-04-23 09:01:58.991917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d7a88bda3d'
down_revision: Union[str, Sequence[str], None] = '2e552fb58f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_access_links', sa.Column('label', sa.String(length=255), nullable=True))
    op.add_column('student_access_links', sa.Column('issued_by_user_id', sa.Integer(), nullable=True))
    op.add_column('student_access_links', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.add_column('student_access_links', sa.Column('usage_count', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('student_access_links', sa.Column('last_device_id', sa.String(length=255), nullable=True))
    op.add_column('student_access_links', sa.Column('last_device_label', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_student_access_links_issued_by_user_id'), 'student_access_links', ['issued_by_user_id'], unique=False)
    op.create_foreign_key(None, 'student_access_links', 'users', ['issued_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_access_links', type_='foreignkey')
    op.drop_index(op.f('ix_student_access_links_issued_by_user_id'), table_name='student_access_links')
    op.drop_column('student_access_links', 'last_device_label')
    op.drop_column('student_access_links', 'last_device_id')
    op.drop_column('student_access_links', 'usage_count')
    op.drop_column('student_access_links', 'revoked_at')
    op.drop_column('student_access_links', 'issued_by_user_id')
    op.drop_column('student_access_links', 'label')
    # ### end Alembic commands ###
