"""add geolocation log and check tables

Revision ID: 93dcc43eb06b
Revises: 585a3b62b415
Create Date: 2026-04-10 10:39:51.291346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93dcc43eb06b'
down_revision: Union[str, Sequence[str], None] = '585a3b62b415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geolocation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('accuracy_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['practice_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geolocation_logs_assignment_id'), 'geolocation_logs', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_geolocation_logs_student_id'), 'geolocation_logs', ['student_id'], unique=False)
    op.create_table('geolocation_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geolocation_log_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('within_radius', sa.Boolean(), nullable=True),
    sa.Column('accuracy_ok', sa.Boolean(), nullable=True),
    sa.Column('time_window_ok', sa.Boolean(), nullable=True),
    sa.Column('check_result', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['practice_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['geolocation_log_id'], ['geolocation_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geolocation_checks_geolocation_log_id'), 'geolocation_checks', ['geolocation_log_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geolocation_checks_geolocation_log_id'), table_name='geolocation_checks')
    op.drop_table('geolocation_checks')
    op.drop_index(op.f('ix_geolocation_logs_student_id'), table_name='geolocation_logs')
    op.drop_index(op.f('ix_geolocation_logs_assignment_id'), table_name='geolocation_logs')
    op.drop_table('geolocation_logs')
    # ### end Alembic commands ###
