"""add supervisor user to practice assignments

Revision ID: c2a314a85f61
Revises: 1da4a4de02e2
Create Date: 2026-04-15 12:54:33.525855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a314a85f61'
down_revision: Union[str, Sequence[str], None] = '1da4a4de02e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_assignments', sa.Column('supervisor_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_practice_assignments_supervisor_user_id'), 'practice_assignments', ['supervisor_user_id'], unique=False)
    op.create_foreign_key(None, 'practice_assignments', 'users', ['supervisor_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_practice_assignments_supervisor_user_id'), table_name='practice_assignments')
    op.drop_column('practice_assignments', 'supervisor_user_id')
    # ### end Alembic commands ###
