"""add student data consents

Revision ID: c50d42cc578c
Revises: 7f7515c6b761
Create Date: 2026-05-04 14:42:47.188776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50d42cc578c'
down_revision: Union[str, Sequence[str], None] = '7f7515c6b761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_data_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=100), nullable=False),
    sa.Column('consent_text_version', sa.String(length=50), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_label', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_data_consents_student_id'), 'student_data_consents', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_data_consents_student_id'), table_name='student_data_consents')
    op.drop_table('student_data_consents')
    # ### end Alembic commands ###
